### ISSUE TITLE
Can't determine temporal order of haystack sessions

### ISSUE THREAD

**Issue by jackaldenryan** [xiaowu0162/LongMemEval#3]
In the final dataset, do haystack_dates, haystack_session_ids, and haystack_sessions all correspond with each other such that e.g. haystack_dates[0] <--> haystack_sessions[0] etc?

From the code, it seems the answer is yes, but the README says that haystack_session_ids is sorted by timestamp, which means it can't correspond with the haystack_dates since those don't seem to be sorted.

Also, thank you for creating this and being so responsive!

**Comment by xiaowu0162** [comment]
Hi @jackaldenryan ,

Thank you for catching this issue. Indeed, "haystack_dates, haystack_session_ids, and haystack_sessions all correspond with each other".  The timestamps in `longmemeval_s.json` and `longmemeval_m.json` should be sorted, but the timestamps in `longmemeval_oracle.json` is in arbitrary order. We have clarified this in the README.

**Comment by jackaldenryan** [comment]
Awesome - thank you for clarifying!
